kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: worksflow-local
networking:
  ipFamily: ipv4
  disableDefaultCNI: true
  apiServerAddress: 127.0.0.1
nodes:
  - role: control-plane
    labels:
      worksflow.dev/runtime: local-qualified-slice
    extraPortMappings:
      - {containerPort: 30080, hostPort: 28080, listenAddress: 127.0.0.1, protocol: TCP}
      - {containerPort: 30443, hostPort: 28443, listenAddress: 127.0.0.1, protocol: TCP}
