DROP TRIGGER IF EXISTS design_import_proposal_independent_apply ON output_proposals;
DROP FUNCTION IF EXISTS prohibit_design_import_creator_proposal_apply();
DROP TRIGGER IF EXISTS design_import_proposal_independent_decision ON proposal_operation_decisions;
DROP FUNCTION IF EXISTS prohibit_design_import_creator_proposal_decision();
DROP TRIGGER IF EXISTS design_import_snapshot_immutable ON design_imports;
DROP FUNCTION IF EXISTS prevent_design_import_snapshot_mutation();
DROP TRIGGER IF EXISTS design_import_state_transition ON design_imports;
DROP FUNCTION IF EXISTS validate_design_import_state_transition();
DROP FUNCTION IF EXISTS design_import_stage_rank(text);
DROP TRIGGER IF EXISTS design_import_tenant_refs ON design_imports;
DROP FUNCTION IF EXISTS validate_design_import_tenant_refs();
DROP TABLE IF EXISTS design_imports;
