import assert from 'node:assert/strict'
import { createGitHubRepository } from '../lib/github/browser-client'
import { HttpClient, type FetchLike } from '../lib/platform/http'

let capturedUrl = ''
let capturedInit: RequestInit | undefined
const http = new HttpClient({
  baseUrl: 'https://platform.example.test/api',
  requestIdFactory: () => 'request-id',
  fetch: (async (input, init) => {
    capturedUrl = input.toString()
    capturedInit = init
    return Response.json({
      result: {
        repository: {
          id: 71,
          name: 'video-platform',
          fullName: 'noir/video-platform',
          owner: 'noir',
          private: true,
          archived: false,
          htmlUrl: 'https://github.com/noir/video-platform',
          defaultBranch: 'main',
          permissions: { pull: true, push: true, admin: true },
        },
        commitSha: 'abc123',
        commitUrl: 'https://github.com/noir/video-platform/commit/abc123',
      },
    }, { status: 201 })
  }) as FetchLike,
})

async function main() {
  const result = await createGitHubRepository(http, 'project/71', {
    owner: 'noir',
    name: 'video-platform',
    description: 'Generated by Worksflow',
    private: true,
    files: [{ path: 'README.md', content: '# Video platform\n' }],
    commitMessage: 'Initialize generated project',
    confirm: true,
  })

  assert.equal(capturedUrl, 'https://platform.example.test/api/v1/projects/project%2F71/github/repositories')
  assert.equal(capturedInit?.method, 'POST')
  assert.ok(new Headers(capturedInit?.headers).get('idempotency-key'))
  assert.deepEqual(JSON.parse(String(capturedInit?.body)), {
    owner: 'noir',
    name: 'video-platform',
    description: 'Generated by Worksflow',
    private: true,
    files: [{ path: 'README.md', content: '# Video platform\n' }],
    commitMessage: 'Initialize generated project',
    confirm: true,
  })
  assert.equal(result.repository.fullName, 'noir/video-platform')
  assert.equal(result.commitSha, 'abc123')
}

void main()
  .then(() => console.log('github browser client tests passed'))
  .catch((error: unknown) => {
    console.error(error)
    process.exitCode = 1
  })
